#
# This is a basic build configuration for Travis CI.
# See http://conda.pydata.org/docs/travis.html for more info.
#

language: python
python:
  - "3.5"

install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda env create -q -n test-environment python=$TRAVIS_PYTHON_VERSION --file environment.yml
  - source activate test-environment
  # conda install -c defaults -c conda-forge pyqt matplotlib xarray dask numpy scipy numba netcdf4 basemap cartopy jdcal libgdal=2.1.0 geopandas
  - python setup.py install

script:
  # For the unit-tests, disable Numba JIT, otherwise Coverage wont reach the actual Python code
  - export NUMBA_DISABLE_JIT=1
  # Uncomment following line if web testing on travis breaks our build
  # - export CATE_DISABLE_WEB_TESTS=1
  - export CATE_DISABLE_PLOT_TESTS=1
  - py.test -v --cov=cate test

after_success:
  - pip install codecov
  - codecov --env TRAVIS_PYTHON_VERSION
