name: cate-docs
channels:
  - defaults
  - conda-forge
dependencies:
  - basemap=1.0.7
  - cartopy=0.14.3
  - numpy=1.11.1
  - scipy=0.18.1
  - xarray=0.8.2
  - dask>=0.11
  - netcdf4=1.2.4
  - jdcal=1.3
  - matplotlib=1.5.3
  - numba>=0.28
  - pyqt=5.6.0
  - qt=5.6.2
  - sphinx>=1.4
  - sphinx_rtd_theme=0.1.9
  - sphinx-argparse
  - pytest-cov=2.3.1
  - hdf4=4.2.12
  - pip:
    - sphinx_autodoc_annotation
    - geopandas
