name: cate-docs
channels:
  - defaults
  - conda-forge
dependencies:
  - basemap=1.0.8.dev0=np111py35_3
  - cartopy=0.14.3=np111py35_4
  - numpy=1.11.1=py35_0
  - scipy=0.18.1=np111py35_0
  - xarray=0.8.2
  - dask>=0.11
  - netcdf4=1.2.4
  - jdcal=1.3
  - matplotlib=1.5.3=np111py35_0
  - numba>=0.28
  - pytest-cov
  - pyqt=5.6.0=py35_0
  - qt=5.6.0=1
  - sphinx>=1.4
  - sphinx_rtd_theme=0.1.9
  - sphinx-argparse
#### locked geopandas deps
  - pandas=0.19.2=np111py35_1
  - hdf4=4.2.12=0
  - click=6.7=py35_0
  - click-plugins=1.0.3=py35_0
  - cligj=0.4.0=py35_0
  - descartes=1.1.0=py35_0
  - munch=2.1.0=py35_0
#### end of geopandas deps
  - pip:
    - sphinx_autodoc_annotation
    - Fiona==1.7.4
    - geopandas==0.2.1
